---
# NOTE: Intended to be run from project root via 'ansible-playbook ansible/host/ssh_config.yml' after a vagrant workspace is created. Will not work as part of the vagrant ansible stack
- name: Add vagrant ssh conf to localhost ssh conf
  hosts: 127.0.0.1
  connection: local
  tasks:
    - set_fact:
        vagrant_machine_ip: "{{ lookup('file', '../../vagrant/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory') | regex_search('\\d+\\.\\d+\\.\\d+\\.\\d+') }}"
    - set_fact:
        vagrant_machine_port: "{{ lookup('file', '../../vagrant/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory') | regex_search('(?<=port=)\\d+') }}"

    - name: Get vagrant machine key short
      shell: ssh-keyscan -t ssh-rsa completedev 2> /dev/null | cut -c 21-
      register: vagrant_machine_key_short

    - name: Get vagrant machine key long
      shell: ssh-keyscan -t ssh-rsa completedev 2> /dev/null | cut -c 12-
      register: vagrant_machine_key_long

    - name: Ensure local ssh conf has the completedev entry present and updated
      ansible.builtin.blockinfile:
        path: "{{ lookup('env', 'HOME') + '/.ssh/config' }}"
        block: |
          Host completedev
               HostName {{ vagrant_machine_ip }}
               User {{ lookup('env', 'USER') }}
               Port {{ vagrant_machine_port }}

    - name: Remove old known_hosts entry
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') + '/.ssh/known_hosts' }}"
        search_string: "{{ vagrant_machine_key_short.stdout }}"
        state: absent

    - name: Remove old known_hosts entry
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') + '/.ssh/known_hosts' }}"
        line: "{{ vagrant_machine_ip + vagrant_machine_key_long.stdout }}"
        state: present
