# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  if Vagrant::Util::Platform::darwin?
    config.vm.box = "bento/ubuntu-20.04-arm64"
  else
    config.vm.box = "bento/ubuntu-20.04"
  end

  config.vm.hostname = "completedev"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  if Vagrant::Util::Platform::darwin?
    config.vm.provider "parallels" do |prl|
      prl.memory = "1024"
      prl.name = "completedev"
      prl.update_guest_tools = true
    end
  else
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "completedev"
      vb.cpus = 1
    end
  end


  #config.vm.provision "ansible" do |ansible|
  #  ansible.playbook = "../../ansible/site.yml"
  #  ansible.compatibility_mode = "2.0"
  #end

end
