- name: Update and upgrade packages
  apt:
    name: "*"
    update_cache: yes
    state: present

- name: Execute shell command
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash - && sudo apt-get install -y nodejs