---
- name: Configure CompleteDev VM
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Install packages for node and ansible management
      import_tasks: ./packages/packages.yml
    - name: Create dev env user and copy over keys
      import_tasks: ./users/usergen.yml
    - name: Pull down Github code repo for dev
      import_tasks: ./code/checkout_project.yml
    - name: Install any needed NodeJS projects
      import_tasks: ./code/install_node_projects.yml
